### ISSUE TITLE
Empty markdown file (“tiddlers.md”) is exported with “export all”, or the “Export tiddlers” with “filter” tab

### ISSUE THREAD

**Issue by anthrolisp** [cdaven/tiddlywiki-stuff#1]
Empty markdown file (“tiddlers.md”) is exported with “export all”, or the “Export tiddlers” with “filter” tab in AdvancedSearch. The same holds whether exported from a Tiddlywiki hosted on Tiddlyhost or stored locally. I am working on Windows, and Firefox. No message outputed to browser console.

**Comment by cdaven** [comment]
I cannot reproduce the error at all.

Which version of TiddlyWiki are you using?

Please update the plugin to the newest version that has a bit more logging built in, and see if the console prints something:

https://cdaven.github.io/tiddlywiki/#%24%3A%2Fplugins%2Fcdaven%2Fmarkdown-export

Make sure that you're not filtering the console, so that debug messages are hidden:

![image](https://user-images.githubusercontent.com/209668/171698942-880d5dc8-9594-4668-a0ab-680e2354fd1c.png)

I suspect that there might be some particular tiddler that doesn't work. What if you try different filters in advanced search, to see if it works for some tiddlers but not others?

**Comment by anthrolisp** [comment]
Perfect. After installing the latest version of the plugin, it's working now. Thank you, and apologies for the trouble!
